name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "videodnmtrrnt-skatebypn"
  comment: "deneme"
  url: "https://str-32.filestore.app/26f71445fbd6c/87e33341a737e/8ef229ffa6cf0?temp_url_expires=1717635559&temp_url_id=b19c0587-ad2a-4d9e-bd2c-7835478ad36c&countable=true&filename=Horny+crowd+jumps+on+a+ripped+stud+in+a+skate+shop_%5BBDSMup.net%5D_.mp4&inline=false&content_type=video%2Fmp4&concurrency=1&rate_limit=25600&response_limit=0&ip_access_policy=first&tags=project%3Ak2s%2Caction%3Adownload%2Cdownload_id%3A43069625984%2Cdownload_type%3Afree%2Cis_server%3Afalse%2Cref_host_id%3A9333%2Cref_uri_id%3A389878789%2Ccountry_code%3ABG%2Cisl%3A89274173%2Cowner_id%3A31464999%2Csite_owner_id%3A31464999%2Csize%3A1936938964%2Cfile_id%3A785550894%2Csite_id%3A14953%2Cuser_pc_id%3Ada6e6d7b6adc6%2Cis_partner_side%3Afalse%2Ccts%3A1717549159%2Cdevice_type%3Adesktop%2Cuser_os%3AWindows%2Cuser_file_id%3Afeb35616f147e%2Cuser_id%3A&temp_url_issuer=5445f78a91de707b297e67ed&temp_url_sig=630d1a59b021ee7f591774197afb605f3fc26d8b87785649213b373646d11bb8799472aa22f47ca33ef4cfbf340a491fd83df49062aa88c7733ee009e15af3d5&client_ip=94.236.214.82"
  file_name: "Horny crowd jumps on a ripped stud in a skate shop_[BDSMup.net]_.mp4"
  piece_size: 2^20 
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
